/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LayoutLayoutRouteImport } from './routes/_layout/layout';
import { Route as PageRouteImport } from './routes/page';
import { Route as LayoutUserLayoutRouteImport } from './routes/_layout/user/layout';
import { Route as LayoutIndexLayoutRouteImport } from './routes/_layout/index/layout';
import { Route as LayoutUserListPageRouteImport } from './routes/_layout/user/list/page';
import { Route as LayoutUserAddPageRouteImport } from './routes/_layout/user/add/page';
import { Route as LayoutIndexDashboardPageRouteImport } from './routes/_layout/index/dashboard/page';

const LayoutLayoutRoute = LayoutLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any);
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutUserLayoutRoute = LayoutUserLayoutRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => LayoutLayoutRoute,
} as any);
const LayoutIndexLayoutRoute = LayoutIndexLayoutRouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => LayoutLayoutRoute,
} as any);
const LayoutUserListPageRoute = LayoutUserListPageRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => LayoutUserLayoutRoute,
} as any);
const LayoutUserAddPageRoute = LayoutUserAddPageRouteImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => LayoutUserLayoutRoute,
} as any);
const LayoutIndexDashboardPageRoute =
  LayoutIndexDashboardPageRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => LayoutIndexLayoutRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof PageRoute;
  '/index': typeof LayoutIndexLayoutRouteWithChildren;
  '/user': typeof LayoutUserLayoutRouteWithChildren;
  '/index/dashboard': typeof LayoutIndexDashboardPageRoute;
  '/user/add': typeof LayoutUserAddPageRoute;
  '/user/list': typeof LayoutUserListPageRoute;
}
export interface FileRoutesByTo {
  '/': typeof PageRoute;
  '/index': typeof LayoutIndexLayoutRouteWithChildren;
  '/user': typeof LayoutUserLayoutRouteWithChildren;
  '/index/dashboard': typeof LayoutIndexDashboardPageRoute;
  '/user/add': typeof LayoutUserAddPageRoute;
  '/user/list': typeof LayoutUserListPageRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof PageRoute;
  '/_layout': typeof LayoutLayoutRouteWithChildren;
  '/_layout/index': typeof LayoutIndexLayoutRouteWithChildren;
  '/_layout/user': typeof LayoutUserLayoutRouteWithChildren;
  '/_layout/index/dashboard/': typeof LayoutIndexDashboardPageRoute;
  '/_layout/user/add/': typeof LayoutUserAddPageRoute;
  '/_layout/user/list/': typeof LayoutUserListPageRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/index'
    | '/user'
    | '/index/dashboard'
    | '/user/add'
    | '/user/list';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/index'
    | '/user'
    | '/index/dashboard'
    | '/user/add'
    | '/user/list';
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/index'
    | '/_layout/user'
    | '/_layout/index/dashboard/'
    | '/_layout/user/add/'
    | '/_layout/user/list/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute;
  LayoutLayoutRoute: typeof LayoutLayoutRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/user': {
      id: '/_layout/user';
      path: '/user';
      fullPath: '/user';
      preLoaderRoute: typeof LayoutUserLayoutRouteImport;
      parentRoute: typeof LayoutLayoutRoute;
    };
    '/_layout/index': {
      id: '/_layout/index';
      path: '/index';
      fullPath: '/index';
      preLoaderRoute: typeof LayoutIndexLayoutRouteImport;
      parentRoute: typeof LayoutLayoutRoute;
    };
    '/_layout/user/list/': {
      id: '/_layout/user/list/';
      path: '/list';
      fullPath: '/user/list';
      preLoaderRoute: typeof LayoutUserListPageRouteImport;
      parentRoute: typeof LayoutUserLayoutRoute;
    };
    '/_layout/user/add/': {
      id: '/_layout/user/add/';
      path: '/add';
      fullPath: '/user/add';
      preLoaderRoute: typeof LayoutUserAddPageRouteImport;
      parentRoute: typeof LayoutUserLayoutRoute;
    };
    '/_layout/index/dashboard/': {
      id: '/_layout/index/dashboard/';
      path: '/dashboard';
      fullPath: '/index/dashboard';
      preLoaderRoute: typeof LayoutIndexDashboardPageRouteImport;
      parentRoute: typeof LayoutIndexLayoutRoute;
    };
  }
}

interface LayoutIndexLayoutRouteChildren {
  LayoutIndexDashboardPageRoute: typeof LayoutIndexDashboardPageRoute;
}

const LayoutIndexLayoutRouteChildren: LayoutIndexLayoutRouteChildren = {
  LayoutIndexDashboardPageRoute: LayoutIndexDashboardPageRoute,
};

const LayoutIndexLayoutRouteWithChildren =
  LayoutIndexLayoutRoute._addFileChildren(LayoutIndexLayoutRouteChildren);

interface LayoutUserLayoutRouteChildren {
  LayoutUserAddPageRoute: typeof LayoutUserAddPageRoute;
  LayoutUserListPageRoute: typeof LayoutUserListPageRoute;
}

const LayoutUserLayoutRouteChildren: LayoutUserLayoutRouteChildren = {
  LayoutUserAddPageRoute: LayoutUserAddPageRoute,
  LayoutUserListPageRoute: LayoutUserListPageRoute,
};

const LayoutUserLayoutRouteWithChildren =
  LayoutUserLayoutRoute._addFileChildren(LayoutUserLayoutRouteChildren);

interface LayoutLayoutRouteChildren {
  LayoutIndexLayoutRoute: typeof LayoutIndexLayoutRouteWithChildren;
  LayoutUserLayoutRoute: typeof LayoutUserLayoutRouteWithChildren;
}

const LayoutLayoutRouteChildren: LayoutLayoutRouteChildren = {
  LayoutIndexLayoutRoute: LayoutIndexLayoutRouteWithChildren,
  LayoutUserLayoutRoute: LayoutUserLayoutRouteWithChildren,
};

const LayoutLayoutRouteWithChildren = LayoutLayoutRoute._addFileChildren(
  LayoutLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  LayoutLayoutRoute: LayoutLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
